# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/MiskoSoft/scb-gateway

  # Spring properties in case you use different profiles
  profiles:
    active: dev